### ISSUE TITLE
Saved variables now undefined in other tests

### ISSUE THREAD

**Issue by damnthem** [taverntesting/tavern#536] opened 2020-04-10 11:09 UTC
After 1.0.0 update variables that was saved in previous test became undefined in further ones.
```
   1 ---
   2 test_name: user_create
   3 
   4 stages:
   5   - name: service ping
   6     request:
.. sensitive data ...
  12     response:
  13       status_code: 200
  14       json:
  15         data: pong.
  16         error: null
  17       save:
  18         $ext:
  19           function: testing_utils:get_shared_ip
  20           extra_kwargs:
  21             server: "{server}"
... some tests that using {shared_ip} ...
  80 ---
  81 test_name: user_modify
.. another tests ...
  96   - name: "Remove personal ips and check it"
  97     request:
.. sensitive data ...
  99       method: POST
 100       json:
 101         ip:
 102           shared:
 103             - "{shared_ip}"
 104       verify: "{verify_crt}"
 105       headers:
 106         Authorization: "{token}"
 107     response:
 108       status_code: 200
 109       verify_response_with:.
 110         function: testing_utils:check_ip_not_exist
 111         extra_kwargs:
 112           check_ip: "{personal_ip}"
```
```
 Key(s) not found in format: shared_ip
   shared_ip = '???'
```
Is this intended? Can't find info about this in change notes.

**Comment by michaelboulton** [comment] 2020-04-10 13:24
This was intended, the previous behaviour was because of a bug where saved variables were not cleared properly between tests. I thought it was fixed in an earlier version but apparently that didn't make it into the changelog, I'll add it now

**Closed by michaelboulton** 2020-04-10 13:24 UTC
