### ISSUE TITLE
Ignore addition fields flag

### ISSUE THREAD

**Issue by lingster** [taverntesting/tavern#201] opened 2018-10-23 06:22 UTC
Hi could one add a feature similar to strict:False so if a response contains addition fields to what is expected then they are ignored. An error would only occur if the specified fields are not there or the values are different. I would be happy to submit a PR and help develop such a feature.

**Comment by michaelboulton** [comment] 2018-11-25 21:04
Could you give an example of how the current setting isn't working with your data? strict: False should already ignore extra fields so I'm not entirely sure what issue you're running in to.

**Comment by michaelboulton** [comment] 2019-01-13 16:02
Closing this issue as I'm not sure what the problem is

**Closed by michaelboulton** 2019-01-13 16:02 UTC

**Comment by lingster** [comment] 2019-01-14 09:12
Hi, sorry I've been a bit busy so when I get a moment I'll try to post an example.of what I mean by this issue.






On Sun, Jan 13, 2019 at 4:04 PM +0000, "michaelboulton" <notifications@github.com> wrote:












Closed #201.
