### ISSUE TITLE
Files upload with @ in path

### ISSUE THREAD

**Issue by optio** [taverntesting/tavern#429] opened 2019-09-02 02:53 UTC
When trying to POST upload a local file, it fails using tavern, while it does work using curl.

Successful curl:
```
curl -X POST "http://localhost:1337/upload/" -H "accept: application/json" -H "Authorization: Bearer myBearerToken" -H "Content-Type: multipart/form-data" -F "files=@/path/to/test_image.png"
```

Failing tavern yaml:

```
- name: POST Image
    request:
      url: "{protocol:s}://{host:s}:{port:d}/upload/"
      method: POST
      headers:
        Authorization: "bearer {myBearerToken:s}"
      files:
        name: "/path/to/test_image.png"
    response:
      status_code: 200
      headers:
        content-type: application/json; charset=utf-8
```

The only difference I notice is that the curl request requires the @ symbol ( https://curl.haxx.se/docs/manpage.html -> --data-binary )
When not prefixing the path with @ using curl, I get the same 400 as I get when using tavern.

The api server is hosted using strapi.io.
Using tavern 0.30.0

**Comment by michaelboulton** [comment] 2019-09-02 12:36
Files in tavern are uploaded using multipart form data, wheras using the @ symbol appears to upload the file as the request body. There is an issue for that here https://github.com/taverntesting/tavern/issues/410  - is this the kind of behaviour you were looking for?

**Comment by optio** [comment] 2019-09-04 04:34
Indeed.
Apparently the @ prefix forces the 'content' part to be a file

**Comment by michaelboulton** [comment] 2019-09-07 14:22
Closing as a duplicate of #410

**Closed by michaelboulton** 2019-09-07 14:22 UTC
