### ISSUE TITLE
i need to change 4.5.0？

### ISSUE THREAD

**Issue by sktt0211** [taverntesting/tavern#498] opened 2019-12-12 09:05 UTC
I can see that

Requirement already satisfied: pyparsing>=2.0.2 in d:\python\lib\site-packages (from packaging->pytest) (2.4.5)
ERROR: tavern 0.30.3 has requirement pytest<4.6.0,>=3.6.0, but you'll have pytest 5.3.1 which is incompatible.
Installing collected packages: pytest

**Comment by frob** [comment] 2019-12-12 15:14
I think this is a duplicate of #367 and should be closed.

**Comment by michaelboulton** [comment] 2020-01-11 17:52
As mentioned in #367 this is due to relying on some internal Pytest behaviour which changed in a recent version - I will look at it again after I've released 1.0 but it might take a while to figure out how the Pytest internals work again.

For the moment, you need to either not specify a version of Pytest in your requirements, or specify `pytest<4.6.0,>=3.6.0`

**Closed by michaelboulton** 2020-01-11 17:52 UTC
