### ISSUE TITLE
PytestDeprecationWarning: direct construction of YamlFile has been deprecated

### ISSUE THREAD

**Issue by AgentOfTech** [taverntesting/tavern#566] opened 2020-07-06 14:45 UTC
I've noticed that I get the following warning each time I run any tests in tavern. No problem with the tests, they run completely fine. I'd like to take care of this warning but it appears it is something that needs updating in the tavern code, rather than something I can take care of. Is that correct? Is this something I need to fix on my side or something the tavern devs need to look into? Thanks:) 

=================================================================================== warnings summary ====================================================================================
/usr/lib/python3.8/site-packages/tavern/testutils/pytesthook/hooks.py:43
  /usr/lib/python3.8/site-packages/tavern/testutils/pytesthook/hooks.py:43: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
    return YamlFile(path, parent)

/usr/lib/python3.8/site-packages/tavern/testutils/pytesthook/file.py:233
  /usr/lib/python3.8/site-packages/tavern/testutils/pytesthook/file.py:233: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item = YamlItem(test_spec["test_name"], self, test_spec, self.fspath)

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by okuryu** [comment] 2020-07-06 23:28
duplicate of #540.

**Comment by AgentOfTech** [comment] 2020-07-07 20:36
Thanks for the info. I realized that I was searching on "open" issues and didn't see this reported anywhere, which is why I entered a new bug. I'll be sure to search all issues before posting any issue in the future. Sorry about that. Thanks again:)

**Comment by michaelboulton** [comment] 2020-07-26 10:10
This still complains in pytest 6 but doesn't raise any errors still

**Closed by michaelboulton** 2020-07-26 10:10 UTC
